project:
  type: website

website:
  title: "Ben Brintz"
  navbar:
    logo: "logo2.png"
    background: "#50C878" 
    left:
      - href: index.qmd
        text: Home
      - href: https://scholar.google.com/citations?user=nYA8PAsAAAAJ&hl=en
        text: Publications
      - href: sierpinski.qmd
        text: Sierpinski Triangle
format:
  html:
    theme: "sandstone"
    toc: false
    css: 
      - custom-layout.css
    

    
execute:
  freeze: auto

  #quarto render --to all