project:
  type: website

website:
  title: "Ben Brintz"
  navbar:
    logo: "logo.png"
    background: "#50C878" 
    left:
      - href: index.qmd
        text: Home
      - href: https://scholar.google.com/citations?user=nYA8PAsAAAAJ&hl=en
        text: Publications
format:
  html:
    theme: "sandstone"
    linkcolor: "#50C878"
    toc: true

    
execute:
  freeze: auto